services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  table_admin_page_manager.wp_globals:
    public: false
    class: Prokl\WordpressCustomTableEditorBundle\Services\Wordpress\WordpressGlobals

  table_admin_page_manager.wpdb:
    public: false
    class: wpdb
    factory: ['@table_admin_page_manager.wp_globals', 'wpdb']

  # Слушатели событий по умолчанию.
  table_admin_page_manager.default_events:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Manager\BaseEventsManager
    arguments: ['@event_dispatcher']

  table_admin_page_manager.collector:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Manager\CollectorEntities
    arguments:
      - '@table_admin_page_manager.wpdb'
      - '@event_dispatcher'
      - '@table_admin_page_manager.default_events'
      - !tagged { tag: wp_custom_table_editable }

  # Инициализация кастомных редакторов таблиц.
  table_admin_page_manager.initialize:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Manager\CollectorEntities
    factory: ['@table_admin_page_manager.collector', 'init']
    tags: ['service.bootstrap']

  admin_custom_table.before_save_init:
    class: Prokl\WordpressCustomTableEditorBundle\Services\CustomEvents\EventsListenerInitializer
    arguments: ['@event_dispatcher', 'admin.custom.table.before.save', !tagged_iterator admin.custom.table.before.save]
    calls:
      - init: []
    tags: ['service.bootstrap']

  # Создатель таблиц.
  table_admin_page_manager.creator_table:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Utils\CreatorTable
    arguments: ['@table_admin_page_manager.wpdb']

  Prokl\WordpressCustomTableEditorBundle\Services\Utils\CreatorTable: '@table_admin_page_manager.creator_table'

  # Создать схему из таблицы
  table_admin_page_manager.creator_schema:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Utils\CreateSchema
    arguments: ['@table_admin_page_manager.wpdb']

  table_admin_page_manager.sql_helper:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Utils\SqlHelper
    arguments: ['@table_admin_page_manager.wpdb']

  # Генератор фикстур
  table_admin_page_manager.fixture_generator:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Utils\FixtureGenerator
    arguments: [!tagged_locator { tag: 'fixture_generator.item' }]

  Prokl\WordpressCustomTableEditorBundle\Services\Utils\FixtureGenerator: '@table_admin_page_manager.fixture_generator'

  # Handler генерации фикстуры текстового поля с ограничением по минимальной и максимальной длине.
  table_admin_page_manager.length_fixture_generator:
    class: Prokl\WordpressCustomTableEditorBundle\Services\FixtureGenerators\DescriptionLength
    arguments: [5, 150]
    tags:
      - { name: fixture_generator.item }

  table_admin_page_manager.seeder_db:
    class: Prokl\WordpressCustomTableEditorBundle\Services\Utils\SeedDatabase
    arguments: ['@table_admin_page_manager.wpdb']

  table_admin_page_manager.real_image_generator:
    class: Prokl\WordpressCustomTableEditorBundle\Services\FixtureGenerators\RealImage
    tags:
      - { name: fixture_generator.item }

  table_admin_page_manager.real_post_generator:
    class: Prokl\WordpressCustomTableEditorBundle\Services\FixtureGenerators\RealPost
    tags:
      - { name: fixture_generator.item }


